server:
  port: 8761
ymlwelcome:
  message: "Service Discovery"
spring:
  security:
    basic:
      enabled: true
    user:
      name: onpassive
      password: onpassive

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    server:
      enableSelfPreservation: true
      waitTimeInMsWhenSynchEmpty: 0

